streams:
  user_actions:
    topic: user_actions
    keyType: string  # user_id
    valueType: json  # action details
    
  user_action_counts:
    topic: user_action_counts
    keyType: string
    valueType: long

pipelines:
  count_by_user:
    from: user_actions
    via:
      - type: groupByKey
      - type: count
      - type: toStream
      - type: peek
        forEach:
          code: |
            log.info("User {} has performed {} actions", key, value)
    to: user_action_counts