streams:
  sensor_readings:
    topic: sensor_readings
    keyType: string
    valueType: json

pipelines:
  main:
    from: sensor_readings
    via:
      - type: groupByKey
      - type: windowByTime
        windowType: tumbling
        duration: 30s
        grace: 5s
      - type: count
        store:
          type: window
          windowSize: 30s
          retention: 1h
          caching: false
      - type: toStream
      - type: peek
        forEach:
          code: log.info("Windowed count - key={}, value={}", key, value)
