streams:
  sensor_readings:
    topic: sensor_readings
    keyType: string
    valueType: json
    
  hourly_sensor_statistics:
    topic: hourly_sensor_statistics
    keyType: json:windowed(string)
    valueType: long

functions:

pipelines:
  main:
    from: sensor_readings
    via:
      - type: groupByKey
      - type: windowByTime
        windowType: tumbling
        duration: 30s
        grace: 5s
      - type: count
        store:
          name: sensor_window_count
          type: window
          windowSize: 30s
          retention: 1h
          caching: false
      - type: toStream
      - type: convertKey
        into: json:windowed(string)
      - type: peek
        forEach:
          code: log.info("WINDOWED COUNT - key={}, value={}", key, value)
    to: hourly_sensor_statistics