functions:
  generate_sensor_reading:
    type: generator
    globalCode: |
      import random
      import time
      sensor_counter = 0
      sensors = ["temp001", "temp002", "temp003", "temp004", "temp005"]
    code: |
      global sensor_counter, sensors

      # Cycle through sensors
      sensor = sensors[sensor_counter % len(sensors)]
      sensor_counter += 1

      # Generate sensor reading
      value = {
        "sensor_id": sensor,
        "temperature": round(random.uniform(18.0, 35.0), 1),
        "timestamp": int(time.time() * 1000)
      }

      # Use sensor_id as key
      key = sensor
    expression: (key, value)
    resultType: (string, json)

producers:
  sensor_producer:
    generator: generate_sensor_reading
    interval: 2s
    to:
      topic: sensor_readings
      keyType: string
      valueType: json
