streams:
  transaction_input:
    topic: transaction_events
    keyType: string
    valueType: json
  region_output:
    topic: transactions_by_region
    keyType: string
    valueType: json

functions:
  extract_region_key:
    type: keyTransformer
    code: |
      # Extract region from transaction data to use as new key
      # This repartitions data by region for region-based analytics
      if value is None:
        return "unknown"
      
      region = value.get("region", "unknown")
      return region
    resultType: string
    
  log_repartitioned:
    type: forEach
    code: |
      log.info("Transaction repartitioned - Original key: {}, New key (region): {}, Amount: ${}", 
               key, value.get("region"), value.get("amount"))

pipelines:
  region_repartitioning:
    from: transaction_input
    via:
      - type: mapKey
        keyTransformer: extract_region_key
      - type: peek
        forEach: log_repartitioned
    to: region_output